version: "3"

services:
    postgres:
        image: postgres:alpine3.14
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: app         
            POSTGRES_USER: django_app
            POSTGRES_PASSWORD: asdasd123
        ports:
            - 5432:5432
        volumes:             
            - ./initial/db:/docker-entrypoint-initdb.d
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - postgres
    djangoapp:
        build: 
            context: .
            dockerfile: ./dockerfiles/python38/Dockerfile
        container_name: djangoapp
        volumes:
            - ./app:/app
            - static:/app/static
            - media:/app/media
        environment:
            - ADDRESS=0.0.0.0
            - PORT=8877
            - SERVER_URL=https://127.0.0.1:5555/ # <- adres lub domena servera cloudowego (wymagane dla swaggera) tutaj wpisz adres na ktorym serwer działa aby inni mieli do niego dostęp
            - DB_ENGINE=django.db.backends.postgresql
            - DB_NAME=app
            - DB_USER=django_app
            - DB_PASSWORD=asdasd123
            - DB_ADDRESS=postgres
            - DB_PORT=5432
            - DB_TESTS=tests
            - DEBUG=0
            - APPSERVER=production
        ports:
            - 8877:8877
        depends_on:
            - postgres
        command: >
            /resources/wait-for-it.sh postgres:5432 --timeout=50 --strict -- /run.sh
    nginx:
        container_name: nginx20
        restart: always
        build:
            context: .
            dockerfile: ./dockerfiles/nginx/Dockerfile
        volumes: 
            - ./logs:/var/log/nginx
            - static:/static/
            - media:/media/
        environment: 
            - UPSTREAM_APP_URL=djangoapp:8877
            - PROXY_PASS=djangoapp
            - HTTP_SERVER_PORT=8833
            - HTTPS_SERVER_PORT=5555
            - SERVER_NAME=default_server_ip # <- adres ip lub domena servera cloudowego
        ports: 
            - "8833:8833"
            - "5555:5555"  
        depends_on: 
            - djangoapp
        command: >
            /resources/wait-for-it.sh djangoapp:8877 --timeout=30 --strict -- /run.sh

volumes: 
    static:
    media: